### ISSUE TITLE
Add github.token as default credential

### ISSUE THREAD

**Issue by RammusXu** [mhausenblas/mkdocs-deploy-gh-pages#28]
ref: https://rammusxu.github.io/toolkit/snippets/github-action/#but-githubtoken-can-be-get-in-actionyaml

It's a little trick.
Do you think it's ok to add this since almost every use this action to deploy in same repo. And default github action have enough permission.
```
# action.yaml
inputs:
  auth_token:
    description: 'Auth token used to API'
    required: true
    default: "${{ github.token }}
```

So, It would be more UX friendly.
```
name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
```
