### ISSUE TITLE
/action.sh: line 42: git: command not found

### ISSUE THREAD

**Issue by allanbowe** [mhausenblas/mkdocs-deploy-gh-pages#87]
I'm getting the following error when running the action - the thing is, I haven't changed anything (that would explain this) since I last pushed, 3 days ago.  

![image](https://user-images.githubusercontent.com/4420615/111041045-8cc8c380-8436-11eb-9d92-2a2a23b8f889.png)

```
/action.sh: line 42: git: command not found
```

My YAML file:

```

name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CUSTOM_DOMAIN: sasjs.io
```

My repository:  https://github.com/sasjs/sasjs.io

I'm getting the same issue on other repositories.

3 days ago, the action ran fine:
![image](https://user-images.githubusercontent.com/4420615/111041034-7e7aa780-8436-11eb-9022-6440b7e14c67.png)
