### ISSUE TITLE
action.sh: line 53: mkdocs: command not found

### ISSUE THREAD

**Issue by Hkr32** [mhausenblas/mkdocs-deploy-gh-pages#93]
Tell me, what am I doing wrong?
If you leave @master, then everything is collected, but the styles are curves

https://github.com/xenforo-ru/docs/runs/2265970611?check_suite_focus=true

**Comment by janoszen** [comment]
@Hkr32 the nomaterial branch does not contain mkdocs, please add a requirements.txt file with the following content:

```
mkdocs
```

This is already reported here, we didn't have time to fix it yet: #80

**Comment by zhuchcn** [comment]
Just in case you really don't want to add a requirement.txt to your repo like me, you can add a step in your workflow yaml before calling mhausenblas/mkdocs-deploy-gh-pages@nomaterial

```
steps:
  - name: Checkout main
    uses: actions/checkout@v2
  
  - name: install mkdocs
    run: echo 'mkdocs' > requirements.txt

  - name: Deploy docs
    uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY }}
      CONFIG_FILE: mkdocs.yml
```
